/**
 * NitinTrace — Export Service
 *
 * Handles exporting trace data in multiple formats:
 * - Markdown report (.md)
 * - JSON data (.json)
 * - Clipboard copy (text/plain)
 */

const APP_NAME = 'NitinTrace';
const APP_VERSION = '1.0.0';
const APP_URL = 'https://n-trace.vercel.app';

// ─── Markdown Export ──────────────────────────────────────────────────────

/**
 * Generate a Markdown report from a trace session.
 * @param {string} code - Source code
 * @param {string} language - Programming language
 * @param {Array<{step: number, line: number, explanation: string, variables: object, console: string}>} steps
 * @returns {string} Markdown content
 */
export function exportToMarkdown(code, language, steps) {
  const date = new Date().toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  });
  const time = new Date().toLocaleTimeString('en-US', {
    hour: '2-digit', minute: '2-digit',
  });

  const lines = [
    `# Execution Trace Report`,
    ``,
    `> Generated by **[${APP_NAME}](${APP_URL})** — AI-Powered Code Execution Visualizer`,
    ``,
    `| Field | Value |`,
    `| --- | --- |`,
    `| **Language** | ${capitalizeFirst(language)} |`,
    `| **Steps** | ${steps.length} |`,
    `| **Date** | ${date} at ${time} |`,
    `| **Tool** | ${APP_NAME} v${APP_VERSION} |`,
    ``,
    `---`,
    ``,
    `## Source Code`,
    ``,
    '```' + language,
    code.trim(),
    '```',
    ``,
    `---`,
    ``,
    `## Execution Trace (${steps.length} step${steps.length === 1 ? '' : 's'})`,
    ``,
  ];

  steps.forEach((step, i) => {
    lines.push(`### Step ${i + 1} — Line ${step.line}`);
    lines.push(``);

    if (step.explanation) {
      lines.push(`**What happens:** ${step.explanation}`);
      lines.push(``);
    }

    if (step.variables && Object.keys(step.variables).length > 0) {
      lines.push(`**Variable State:**`);
      lines.push(``);
      lines.push(`| Variable | Value | Type |`);
      lines.push(`| --- | --- | --- |`);
      for (const [key, value] of Object.entries(step.variables)) {
        const type = Array.isArray(value) ? 'array' : typeof value;
        const display = formatValueForMarkdown(value);
        lines.push(`| \`${key}\` | \`${display}\` | ${type} |`);
      }
      lines.push(``);
    }

    if (step.console) {
      lines.push(`**Console Output:**`);
      lines.push(``);
      lines.push('```');
      lines.push(String(step.console).trim());
      lines.push('```');
      lines.push(``);
    }

    if (i < steps.length - 1) {
      lines.push(`---`);
      lines.push(``);
    }
  });

  lines.push(`---`);
  lines.push(``);
  lines.push(`*Traced with [${APP_NAME}](${APP_URL}) — the AI-powered code execution visualizer.*`);
  lines.push(``);

  return lines.join('\n');
}

// ─── JSON Export ──────────────────────────────────────────────────────────

/**
 * Generate a structured JSON export of a trace session.
 * @param {string} code
 * @param {string} language
 * @param {Array} steps
 * @returns {string} Formatted JSON string
 */
export function exportToJSON(code, language, steps) {
  const payload = {
    meta: {
      app: APP_NAME,
      version: APP_VERSION,
      url: APP_URL,
      exportedAt: new Date().toISOString(),
      format: 'nitintrace-trace-v1',
    },
    trace: {
      language,
      stepCount: steps.length,
      code: code.trim(),
      steps: steps.map((s, i) => ({
        index: i,
        step: s.step ?? i + 1,
        line: s.line,
        explanation: s.explanation || '',
        variables: s.variables || {},
        console: s.console || '',
        callStack: s.callStack || [],
      })),
    },
  };
  return JSON.stringify(payload, null, 2);
}

// ─── Clipboard Copy ───────────────────────────────────────────────────────

/**
 * Copy trace summary as plain text to clipboard.
 * @param {string} code
 * @param {string} language
 * @param {Array} steps
 * @param {number} [currentStep] - If provided, copies only the current step
 * @returns {Promise<boolean>} true if successful
 */
export async function copyToClipboard(code, language, steps, currentStep) {
  let text;

  if (typeof currentStep === 'number' && steps[currentStep]) {
    const s = steps[currentStep];
    const varEntries = s.variables
      ? Object.entries(s.variables).map(([k, v]) => `  ${k} = ${formatValue(v)}`).join('\n')
      : '';

    text = [
      `[${APP_NAME}] Step ${currentStep + 1}/${steps.length} — ${capitalizeFirst(language)}`,
      `Line ${s.line}: ${s.explanation || ''}`,
      varEntries ? `Variables:\n${varEntries}` : '',
      s.console ? `Output: ${s.console}` : '',
      ``,
      `Traced with ${APP_URL}`,
    ].filter(Boolean).join('\n');
  } else {
    // Copy a brief text summary of the full trace
    text = [
      `[${APP_NAME}] Execution Trace — ${capitalizeFirst(language)}`,
      `${steps.length} step${steps.length === 1 ? '' : 's'} traced`,
      ``,
      ...steps.slice(0, 10).map((s, i) => `Step ${i + 1} (Line ${s.line}): ${s.explanation || ''}`),
      steps.length > 10 ? `... and ${steps.length - 10} more steps` : '',
      ``,
      `Traced with ${APP_URL}`,
    ].filter(Boolean).join('\n');
  }

  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    // Fallback for environments without clipboard API
    return legacyCopy(text);
  }
}

/**
 * Fallback clipboard copy using a temporary textarea.
 * @param {string} text
 * @returns {boolean}
 */
function legacyCopy(text) {
  try {
    const ta = document.createElement('textarea');
    ta.value = text;
    ta.style.position = 'fixed';
    ta.style.opacity = '0';
    document.body.appendChild(ta);
    ta.select();
    const ok = document.execCommand('copy');
    document.body.removeChild(ta);
    return ok;
  } catch {
    return false;
  }
}

// ─── File Download ────────────────────────────────────────────────────────

/**
 * Trigger a browser file download.
 * @param {string} content - File content string
 * @param {string} filename - Download filename
 * @param {string} mimeType - MIME type (e.g. 'text/markdown', 'application/json')
 */
export function downloadAsFile(content, filename, mimeType) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.style.display = 'none';
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  // Revoke after a short delay to allow the download to start
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

// ─── Convenience Methods ──────────────────────────────────────────────────

/**
 * Download trace as Markdown file.
 * @param {string} code
 * @param {string} language
 * @param {Array} steps
 */
export function downloadMarkdown(code, language, steps) {
  const content = exportToMarkdown(code, language, steps);
  const langSlug = language.toLowerCase().replace(/\s+/g, '-');
  const filename = `nitintrace-${langSlug}-${dateSlug()}.md`;
  downloadAsFile(content, filename, 'text/markdown;charset=utf-8');
}

/**
 * Download trace as JSON file.
 * @param {string} code
 * @param {string} language
 * @param {Array} steps
 */
export function downloadJSON(code, language, steps) {
  const content = exportToJSON(code, language, steps);
  const langSlug = language.toLowerCase().replace(/\s+/g, '-');
  const filename = `nitintrace-${langSlug}-${dateSlug()}.json`;
  downloadAsFile(content, filename, 'application/json;charset=utf-8');
}

// ─── Private Helpers ──────────────────────────────────────────────────────

function capitalizeFirst(str) {
  if (!str) return '';
  return str.charAt(0).toUpperCase() + str.slice(1);
}

function dateSlug() {
  return new Date().toISOString().slice(0, 10); // e.g. 2026-06-27
}

function formatValue(val) {
  if (val === null) return 'null';
  if (val === undefined) return 'undefined';
  if (typeof val === 'string') return `"${val}"`;
  if (Array.isArray(val)) return `[${val.join(', ')}]`;
  if (typeof val === 'object') return JSON.stringify(val);
  return String(val);
}

function formatValueForMarkdown(val) {
  const s = formatValue(val);
  // Escape markdown table pipe characters
  return s.replace(/\|/g, '\\|').replace(/\n/g, ' ');
}
